name:                webbi
version:             0.1.0.0
github:              "githubuser/webbi"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/webbi#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll
- clay
- blaze-html
- comonad
- containers
- filepath
- extra
- pandoc
- text
- bytestring
- process
- mtl

- tasty
- tasty-hunit
- tasty-quickcheck

- dhall

- lens
- generic-lens

- dlist


default-extensions:
- OverloadedStrings
- DerivingStrategies
- DeriveFunctor

library:
  source-dirs: src

executables:
  webbi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webbi

tests:
  webbi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - webbi
